# Generated by Django 5.1.3 on 2025-01-15 14:12

import django.db.models.deletion
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('holiday_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
            },
        ),
        migrations.CreateModel(
            name='HudumaCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=80)),
                ('id_number', models.CharField(max_length=20, null=True, unique=True)),
                ('personal_number', models.CharField(max_length=20, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('designation', models.CharField(blank=True, choices=[('ICT', 'ICT'), ('TEA GIRL', 'TEA GIRL'), ('CUSTOMER CARE', 'CUSTOMER CARE'), ('GENERAL DUTIES', 'GENERAL DUTIES'), ('SUPPORT STAFF', 'SUPPORT STAFF')], max_length=50, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to=user.models.generate_unique_name)),
                ('email', models.EmailField(max_length=110, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_CEO', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('total_leave_days', models.IntegerField(default=0)),
                ('huduma_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='user.hudumacentre', verbose_name='Huduma Centre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SL', 'Sick Leave'), ('CL', 'Casual Leave'), ('EL', 'Emergency Leave')], max_length=2)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('description', models.TextField()),
                ('posting_date', models.DateTimeField(auto_now_add=True)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('admin_remark_date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10)),
                ('no_of_days', models.IntegerField(default=15, verbose_name='Number of Days')),
                ('carry_forward_days', models.IntegerField(default=0, verbose_name='Carry Forward Days')),
                ('total_leave_days', models.IntegerField(default=0, verbose_name='Total Leave Days')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
