# Generated by Django 3.2.23 on 2024-12-06 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SL', 'Sick Leave'), ('CL', 'Casual Leave'), ('PL', 'Paid Leave'), ('EL', 'Emergency Leave')], max_length=2, verbose_name='Leave Type')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('posting_date', models.DateTimeField(auto_now_add=True, verbose_name='Posting Date')),
                ('admin_remarks', models.TextField(blank=True, null=True, verbose_name='Admin Remarks')),
                ('admin_remark_date', models.DateTimeField(blank=True, null=True, verbose_name='Admin Remark Date')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10, verbose_name='Status')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
        ),
    ]
