# Generated by Django 5.1.3 on 2024-12-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_leaveapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='admin_remark_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='admin date'),
        ),
    ]
