# Generated by Django 5.1.3 on 2024-12-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_account_huduma_centre_account_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='account',
            name='total_leave_days',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='admin_remark_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='total_leave_days',
            field=models.IntegerField(default=0, verbose_name='Total Leave Days'),
        ),
    ]
