# Generated by Django 3.2.23 on 2024-12-25 08:34

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_account_modified_date_account_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HudumaCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='is_CEO',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='designation',
            field=models.CharField(blank=True, choices=[('ICT', 'ICT'), ('TEA GIRL', 'TEA GIRL'), ('CUSTOMER CARE', 'CUSTOMER CARE'), ('GENERAL DUTIES', 'GENERAL DUTIES'), ('SUPPORT STAFF', 'SUPPORT STAFF')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=user.models.generate_unique_name),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_leave_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='huduma_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='user.hudumacentre', verbose_name='Huduma Centre'),
        ),
    ]
