# Generated by Django 5.1.3 on 2024-12-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_account_modified_date_account_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='designation',
            field=models.CharField(blank=True, choices=[('iCT', 'ICT'), ('TEA GIRL', 'TEA GIRL'), ('CUSTOMER CARE', 'CUSTOMER CARE'), ('GENERAL DUTIES', 'GENERAL DUTIES'), ('SUPPORT STAFF', 'SUPPORT STAFF')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_leave_days',
            field=models.IntegerField(default=0),
        ),
    ]
