# Generated by Django 5.1.3 on 2024-12-21 08:38

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_account_huduma_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='designation',
            field=models.CharField(blank=True, choices=[('ICT', 'ICT'), ('TEA GIRL', 'TEA GIRL'), ('CUSTOMER CARE', 'CUSTOMER CARE'), ('GENERAL DUTIES', 'GENERAL DUTIES'), ('SUPPORT STAFF', 'SUPPORT STAFF')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=user.models.generate_unique_name),
        ),
    ]
