# Generated by Django 5.1.3 on 2024-12-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_is_staff_account_is_ceo_account_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
