# Generated by Django 3.2.23 on 2025-01-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20241225_1134'),
        ('user', '0015_account_is_staff'),
    ]

    operations = [
    ]
